version: 1

# 👇 Runtime override to force Node.js 20
frontend:
  runtime:
    name: nodejs
    version: 20

  phases:
    preBuild:
      commands:
        - echo "Using Node version:"
        - node -v
        - npm ci
    build:
      commands:
        - npm run build

  artifacts:
    baseDirectory: dist
    files:
      - '**/*'

  cache:
    paths:
      - .npm/**/*

backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
