version: 1

# ✅ MUST be at root level — not under `frontend`
runtime:
  name: nodejs
  version: 20

frontend:
  phases:
    preBuild:
      commands:
        - echo "Using Node version:"
        - node -v
        - npm ci
    build:
      commands:
        - npm run build

  artifacts:
    baseDirectory: dist
    files:
      - '**/*'

  cache:
    paths:
      - .npm/**/*

backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
